version: "3"

services:
    fava:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: fava
        restart: always
        environment:
            - BEANCOUNT_FILE=/bean/main.bean
            - PYTHONPATH=/bean
            - FAVA_HOST=0.0.0.0
        volumes:
            - ./:/bean
        networks:
            - caddy_net

    caddy:
        image: caddy:latest
        container_name: caddy
        restart: always
        ports:
            - "80:80"
            - "443:443"
        extra_hosts:
            - "host.docker.internal:host-gateway"
        volumes:
            - ./Caddyfile:/etc/caddy/Caddyfile
            - caddy_data:/data
            - caddy_config:/config
        depends_on:
            - fava
        networks:
            - caddy_net

volumes:
    caddy_data:
    caddy_config:

networks:
    caddy_net:
        external: true
